--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/gamesukimanIRS/IRSPlugins
branches:
- master
projects:
  Elevator:
    path: Elevator/
  Jisatu:
    path: Jisatu/
  ServerTitle:
    path: ServerTitle/
  getCUUID:
    path: getCUUID/
  xyzplugin:
    path: xyzplugin/
...
